"""empty message

Revision ID: 09686be12a40
Revises: d8da60c985fd
Create Date: 2016-06-09 17:56:41.569914

"""

# revision identifiers, used by Alembic.
revision = '09686be12a40'
down_revision = 'd8da60c985fd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_invitation')
    op.add_column('user', sa.Column('income', sa.SmallInteger(), nullable=True))
    op.add_column('user', sa.Column('industry', sa.SmallInteger(), nullable=True))
    op.drop_column('work_experience', 'industry_id')
    op.drop_column('work_experience', 'income')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_experience', sa.Column('income', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('work_experience', sa.Column('industry_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('user', 'industry')
    op.drop_column('user', 'income')
    op.create_table('user_invitation',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('invitation_type', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('description', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
