"""empty message

Revision ID: 0b2d9c2fcd46
Revises: d471ec781b14
Create Date: 2016-06-10 16:26:10.436085

"""

# revision identifiers, used by Alembic.
revision = '0b2d9c2fcd46'
down_revision = 'd471ec781b14'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_detail', 'photo')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_detail', sa.Column('photo', mysql.VARCHAR(length=3000), nullable=True))
    ### end Alembic commands ###
