"""empty message

Revision ID: 2fa3c13e40cb
Revises: a61b7ca1ee23
Create Date: 2016-06-13 11:33:02.401189

"""

# revision identifiers, used by Alembic.
revision = '2fa3c13e40cb'
down_revision = 'a61b7ca1ee23'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagement_order', sa.Column('uuid', sa.String(length=32), nullable=False))
    op.drop_column('engagement_order', 'id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagement_order', sa.Column('id', mysql.INTEGER(display_width=11), nullable=False))
    op.drop_column('engagement_order', 'uuid')
    ### end Alembic commands ###
