"""empty message

Revision ID: 485e57981eb2
Revises: f32f3a53fa35
Create Date: 2016-06-09 10:37:59.583240

"""

# revision identifiers, used by Alembic.
revision = '485e57981eb2'
down_revision = 'f32f3a53fa35'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'industry_id')
    op.drop_column('user', 'profession')
    op.drop_column('user', 'company_name')
    op.drop_column('user', 'income')
    op.drop_column('user', 'graduated')
    op.drop_column('user', 'education')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('education', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('graduated', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('user', sa.Column('income', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('company_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('user', sa.Column('profession', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('user', sa.Column('industry_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
