"""empty message

Revision ID: 4d0374215543
Revises: 3afd23e3a1a8
Create Date: 2016-06-06 19:00:27.988897

"""

# revision identifiers, used by Alembic.
revision = '4d0374215543'
down_revision = '3afd23e3a1a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('photo', sa.String(length=3000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_photo')
    ### end Alembic commands ###
