"""empty message

Revision ID: 55e520b662de
Revises: af94fec1c5b5
Create Date: 2016-06-12 17:12:29.754941

"""

# revision identifiers, used by Alembic.
revision = '55e520b662de'
down_revision = 'af94fec1c5b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagement_order', sa.Column('description', sa.String(length=5000), nullable=True))
    op.add_column('engagement_order', sa.Column('theme', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('engagement_order', 'theme')
    op.drop_column('engagement_order', 'description')
    ### end Alembic commands ###
