"""empty message

Revision ID: 5714d1519aee
Revises: d14e54753bfb
Create Date: 2016-06-15 17:50:34.478809

"""

# revision identifiers, used by Alembic.
revision = '5714d1519aee'
down_revision = 'd14e54753bfb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('longtitude', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'longtitude')
    op.drop_column('user', 'latitude')
    ### end Alembic commands ###
