"""empty message

Revision ID: 57302998d431
Revises: 5f4877ff3273
Create Date: 2016-06-13 16:23:06.482181

"""

# revision identifiers, used by Alembic.
revision = '57302998d431'
down_revision = '5f4877ff3273'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.add_column(u'user', sa.Column('job_label', sa.String(length=2000), nullable=True))
    op.add_column(u'user', sa.Column('personal_label', sa.String(length=2000), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user', 'personal_label')
    op.drop_column(u'user', 'job_label')
    op.drop_table('tag')
    ### end Alembic commands ###
