"""empty message

Revision ID: 951b0cbf24a4
Revises: 55e520b662de
Create Date: 2016-06-13 11:29:16.291777

"""

# revision identifiers, used by Alembic.
revision = '951b0cbf24a4'
down_revision = '55e520b662de'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'engagement_order_ibfk_1', 'engagement_order', type_='foreignkey')
    op.drop_column('engagement_order', 'guest')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagement_order', sa.Column('guest', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key(u'engagement_order_ibfk_1', 'engagement_order', 'user', ['guest'], ['id'])
    ### end Alembic commands ###
