"""empty message

Revision ID: 9eaf5cbc36a7
Revises: b2bbe6c07ddb
Create Date: 2016-06-10 13:53:16.738342

"""

# revision identifiers, used by Alembic.
revision = '9eaf5cbc36a7'
down_revision = 'b2bbe6c07ddb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagement_order', sa.Column('created', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('engagement_order', 'created')
    ### end Alembic commands ###
