"""empty message

Revision ID: af94fec1c5b5
Revises: 0b2d9c2fcd46
Create Date: 2016-06-10 16:26:25.980548

"""

# revision identifiers, used by Alembic.
revision = 'af94fec1c5b5'
down_revision = '0b2d9c2fcd46'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_detail', sa.Column('photo', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_detail', 'photo')
    ### end Alembic commands ###
