"""empty message

Revision ID: cc4dc958b64c
Revises: None
Create Date: 2016-06-04 10:57:41.324932

"""

# revision identifiers, used by Alembic.
revision = 'cc4dc958b64c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('social_id', sa.String(length=100), nullable=True),
    sa.Column('wechat_union_id', sa.String(length=100), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('gender', sa.SmallInteger(), nullable=True),
    sa.Column('user_name', sa.String(length=40), nullable=False),
    sa.Column('real_name', sa.String(length=40), nullable=True),
    sa.Column('id_card', sa.String(length=40), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('mobile_num', sa.String(length=20), nullable=True),
    sa.Column('weixin_num', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('industry_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('profession', sa.String(length=100), nullable=True),
    sa.Column('affection', sa.SmallInteger(), nullable=True),
    sa.Column('income', sa.SmallInteger(), nullable=True),
    sa.Column('graduated', sa.String(length=100), nullable=True),
    sa.Column('education', sa.SmallInteger(), nullable=True),
    sa.Column('hometown', sa.String(length=100), nullable=True),
    sa.Column('drink', sa.SmallInteger(), nullable=True),
    sa.Column('smoke', sa.SmallInteger(), nullable=True),
    sa.Column('constellation', sa.SmallInteger(), nullable=True),
    sa.Column('religion', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_mobile_num'), 'user', ['mobile_num'], unique=False)
    op.create_index(op.f('ix_user_user_name'), 'user', ['user_name'], unique=False)
    op.create_table('user_info',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('photos', sa.String(length=3000), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('auth_info', sa.String(length=3000), nullable=True),
    sa.Column('detail', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('invitation_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=7), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_invitation_code_code'), 'invitation_code', ['code'], unique=True)
    op.create_table('user_invitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('invitation_type', sa.SmallInteger(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_invitation_user_id'), 'user_invitation', ['user_id'], unique=False)
    op.create_table('privilege',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('industry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('industry')
    op.drop_table('privilege')
    op.drop_index(op.f('ix_user_invitation_user_id'), table_name='user_invitation')
    op.drop_table('user_invitation')
    op.drop_index(op.f('ix_invitation_code_code'), table_name='invitation_code')
    op.drop_table('invitation_code')
    op.drop_table('user_info')
    op.drop_index(op.f('ix_user_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_mobile_num'), table_name='user')
    op.drop_table('user')
    ### end Alembic commands ###
