"""empty message

Revision ID: d14e54753bfb
Revises: 3fc9033213b6
Create Date: 2016-06-14 16:04:15.447722

"""

# revision identifiers, used by Alembic.
revision = 'd14e54753bfb'
down_revision = '3fc9033213b6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('privilege')
    op.add_column('engagement_order', sa.Column('uuid', sa.String(length=2), nullable=False))
    op.drop_column('engagement_order', 'id')
    op.create_unique_constraint(None, 'job_label', ['name'])
    op.create_unique_constraint(None, 'personal_label', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'personal_label', type_='unique')
    op.drop_constraint(None, 'job_label', type_='unique')
    op.add_column('engagement_order', sa.Column('id', mysql.VARCHAR(length=32), nullable=False))
    op.drop_column('engagement_order', 'uuid')
    op.create_table('privilege',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
