"""empty message

Revision ID: d471ec781b14
Revises: d73e61f53865
Create Date: 2016-06-10 16:21:39.935654

"""

# revision identifiers, used by Alembic.
revision = 'd471ec781b14'
down_revision = 'd73e61f53865'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_detail', sa.Column('photo', sa.String(length=3000), nullable=True))
    op.add_column('user_info', sa.Column('cover_photo', sa.String(length=1000), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'cover_photo')
    op.drop_column('user_detail', 'photo')
    ### end Alembic commands ###
