"""empty message

Revision ID: d5717ecfe7e7
Revises: 5714d1519aee
Create Date: 2016-06-15 17:51:24.674238

"""

# revision identifiers, used by Alembic.
revision = 'd5717ecfe7e7'
down_revision = '5714d1519aee'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('laititude', sa.Float(), nullable=True))
    op.drop_column('user', 'latitude')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('latitude', mysql.FLOAT(), nullable=True))
    op.drop_column('user', 'laititude')
    ### end Alembic commands ###
