"""empty message

Revision ID: d73e61f53865
Revises: 9eaf5cbc36a7
Create Date: 2016-06-10 16:10:56.255307

"""

# revision identifiers, used by Alembic.
revision = 'd73e61f53865'
down_revision = '9eaf5cbc36a7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_info_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('content', sa.String(length=3000), nullable=True),
    sa.ForeignKeyConstraint(['user_info_id'], ['user_info.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_column(u'user_info', 'photos')
    op.drop_column(u'user_info', 'detail')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'user_info', sa.Column('detail', sa.BLOB(), nullable=True))
    op.add_column(u'user_info', sa.Column('photos', mysql.VARCHAR(length=3000), nullable=True))
    op.drop_table('user_detail')
    ### end Alembic commands ###
