"""empty message

Revision ID: d8da60c985fd
Revises: 485e57981eb2
Create Date: 2016-06-09 11:34:15.248993

"""

# revision identifiers, used by Alembic.
revision = 'd8da60c985fd'
down_revision = '485e57981eb2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edu_experience', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('work_experience', sa.Column('created', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_experience', 'created')
    op.drop_column('edu_experience', 'created')
    ### end Alembic commands ###
