"""empty message

Revision ID: ddc5239023b3
Revises: c90b855eecf6
Create Date: 2016-06-10 11:02:06.513506

"""

# revision identifiers, used by Alembic.
revision = 'ddc5239023b3'
down_revision = 'c90b855eecf6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('app_version', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('device_token', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('mobile_model', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('os_version', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('system_language', sa.String(length=30), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'system_language')
    op.drop_column('user', 'os_version')
    op.drop_column('user', 'mobile_model')
    op.drop_column('user', 'device_token')
    op.drop_column('user', 'app_version')
    ### end Alembic commands ###
