"""empty message

Revision ID: f32f3a53fa35
Revises: fb85f1227e84
Create Date: 2016-06-07 16:51:19.438007

"""

# revision identifiers, used by Alembic.
revision = 'f32f3a53fa35'
down_revision = 'fb85f1227e84'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_column(u'engagement', 'theme')
    op.drop_column(u'engagement', 'price')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'engagement', sa.Column('price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column(u'engagement', sa.Column('theme', mysql.VARCHAR(length=100), nullable=True))
    op.drop_table('theme')
    ### end Alembic commands ###
